-- Seed: lora_catalog from Thunder worker inventory (2026-09-03)
-- Run in: Supabase Dashboard > SQL Editor  (after 20260903_002_lora_catalog.sql)
-- Generated automatically from worker file listing; edit freely.

INSERT INTO lora_catalog (worker_filename, name, base_model, lane, tags, recommended_strength, source, purchase_status)
VALUES
  ('KLEIN-Unchained-V2.safetensors', 'Klein-Unchained-V2', 'flux2-klein', 'stills', ARRAY['flux2-klein', 'stills'], 0.7, 'civitai', 'owned'),
  ('Klein9BGeneralPenis-v1-5BETA.safetensors', 'Klein9Bgeneralpenis-V1-5Beta', 'flux2-klein', 'stills', ARRAY['flux2-klein', 'stills'], 0.7, 'civitai', 'owned'),
  ('KleinAnatomy_Male.safetensors', 'Kleinanatomy Male', 'flux2-klein', 'stills', ARRAY['flux2-klein', 'stills'], 0.7, 'civitai', 'owned'),
  ('Klein_Anatomy.safetensors', 'Klein Anatomy', 'flux2-klein', 'stills', ARRAY['flux2-klein', 'stills'], 0.7, 'civitai', 'owned'),
  ('MalePenis_Klein9B_v0.2.safetensors', 'Malepenis Klein9B V0.2', 'flux2-klein', 'stills', ARRAY['flux2-klein', 'stills'], 0.7, 'civitai', 'owned'),
  ('Male_Nude_and_Genital_Anatomy_for_Flux_1_Dev.safetensors', 'Male Nude And Genital Anatomy For Flux 1 Dev', 'flux2-klein', 'stills', ARRAY['flux2-klein', 'stills'], 0.7, 'civitai', 'owned'),
  ('SEXGOD_Blowjobs_Klein9b_v1.safetensors', 'Sexgod Blowjobs Klein9B V1', 'flux2-klein', 'stills', ARRAY['flux2-klein', 'stills'], 0.7, 'civitai', 'owned'),
  ('SEXGOD_CouplesNudity_Klein9b_v2.safetensors', 'Sexgod Couplesnudity Klein9B V2', 'flux2-klein', 'stills', ARRAY['flux2-klein', 'stills'], 0.7, 'civitai', 'owned'),
  ('SEXGOD_ImprovedNudity_Klein9b_v4.safetensors', 'Sexgod Improvednudity Klein9B V4', 'flux2-klein', 'stills', ARRAY['flux2-klein', 'stills'], 0.7, 'civitai', 'owned'),
  ('SexGod_Doggystyle_Klein9b_v1.safetensors', 'Sexgod Doggystyle Klein9B V1', 'flux2-klein', 'stills', ARRAY['flux2-klein', 'stills'], 0.7, 'civitai', 'owned'),
  ('flux.2-klein-9b-penis-coachbate-v2.safetensors', 'Flux.2-Klein-9B-Penis-Coachbate-V2', 'flux2-klein', 'stills', ARRAY['flux2-klein', 'stills'], 0.7, 'civitai', 'owned'),
  ('shexyo_style_klein9b.safetensors', 'Shexyo Style Klein9B', 'flux2-klein', 'stills', ARRAY['flux2-klein', 'stills'], 0.7, 'civitai', 'owned'),
  ('HMPenis_v2.0_H3.safetensors', 'Hmpenis V2.0 H3', 'h3', 'video', ARRAY['h3', 'video'], 0.7, 'civitai', 'owned'),
  ('PenisLora_H3_v1.1.safetensors', 'Penislora H3 V1.1', 'h3', 'video', ARRAY['h3', 'video'], 0.7, 'civitai', 'owned'),
  ('minimax_h3_fl2v_lightx2v_turbo_4step_v1.0_768p_resized_avg_rank_31_bf16.safetensors', 'Minimax H3 Fl2V Lightx2V Turbo 4Step V1.0 768P Resized Avg Rank 31 Bf16', 'h3', 'video', ARRAY['h3', 'video'], 0.7, 'civitai', 'owned'),
  ('minimax_h3_fl2v_lightx2v_turbo_8step_v1.0_resized_avg_rank_24_bf16.safetensors', 'Minimax H3 Fl2V Lightx2V Turbo 8Step V1.0 Resized Avg Rank 24 Bf16', 'h3', 'video', ARRAY['h3', 'video'], 0.7, 'civitai', 'owned'),
  ('minimax_h3_ref2v_lightx2v_turbo_4step_v0.1_resized_avg_rank_20_bf16.safetensors', 'Minimax H3 Ref2V Lightx2V Turbo 4Step V0.1 Resized Avg Rank 20 Bf16', 'h3', 'video', ARRAY['h3', 'video'], 0.7, 'civitai', 'owned'),
  ('2.2-I2V-Hi-SexyMove.safetensors', '2.2-I2V-Hi-Sexymove', 'krea2', 'both', ARRAY['krea2', 'both'], 0.7, 'civitai', 'owned'),
  ('2.2-I2V-Hi-femPOV.safetensors', '2.2-I2V-Hi-Fempov', 'krea2', 'both', ARRAY['krea2', 'both'], 0.7, 'civitai', 'owned'),
  ('BLACKED_KREA2v0.safetensors', 'Blacked Krea2V0', 'krea2', 'stills', ARRAY['krea2', 'stills'], 0.7, 'civitai', 'owned'),
  ('Damp_Armpit_v1_Full_Krea2.safetensors', 'Damp Armpit V1 Full Krea2', 'krea2', 'stills', ARRAY['krea2', 'stills'], 0.7, 'civitai', 'owned'),
  ('Damp_Armpit_v1_ba_Krea2.safetensors', 'Damp Armpit V1 Ba Krea2', 'krea2', 'stills', ARRAY['krea2', 'stills'], 0.7, 'civitai', 'owned'),
  ('KNPV4.1_pre.safetensors', 'Knpv4.1 Pre', 'krea2', 'both', ARRAY['krea2', 'both'], 0.7, 'civitai', 'owned'),
  ('Krea2_FinalCut_FP8.safetensors', 'Krea2 Finalcut Fp8', 'krea2', 'stills', ARRAY['krea2', 'stills'], 0.7, 'civitai', 'owned'),
  ('Krea2_TextFusion_Refusal_Reduction.safetensors', 'Krea2 Textfusion Refusal Reduction', 'krea2', 'stills', ARRAY['krea2', 'stills'], 0.7, 'civitai', 'owned'),
  ('Krea_2_innie_rank_32.safetensors', 'Krea 2 Innie Rank 32', 'krea2', 'stills', ARRAY['krea2', 'stills'], 0.7, 'civitai', 'owned'),
  ('Male_Anatomy-v2.02-ep4.safetensors', 'Male Anatomy-V2.02-Ep4', 'krea2', 'both', ARRAY['krea2', 'both'], 0.7, 'civitai', 'owned'),
  ('bbc-blowjob.safetensors', 'Bbc-Blowjob', 'krea2', 'both', ARRAY['krea2', 'both'], 0.7, 'civitai', 'owned'),
  ('bbc-ride.safetensors', 'Bbc-Ride', 'krea2', 'both', ARRAY['krea2', 'both'], 0.7, 'civitai', 'owned'),
  ('bodyshots-high.safetensors', 'Bodyshots-High', 'krea2', 'both', ARRAY['krea2', 'both'], 0.7, 'civitai', 'owned'),
  ('bodyshots-low.safetensors', 'Bodyshots-Low', 'krea2', 'both', ARRAY['krea2', 'both'], 0.7, 'civitai', 'owned'),
  ('ebony-body.safetensors', 'Ebony-Body', 'krea2', 'both', ARRAY['krea2', 'both'], 0.7, 'civitai', 'owned'),
  ('ebony-face.safetensors', 'Ebony-Face', 'krea2', 'both', ARRAY['krea2', 'both'], 0.7, 'civitai', 'owned'),
  ('fingering_i2v_e248.safetensors', 'Fingering I2V E248', 'krea2', 'both', ARRAY['krea2', 'both'], 0.7, 'civitai', 'owned'),
  ('flatchested-high.safetensors', 'Flatchested-High', 'krea2', 'both', ARRAY['krea2', 'both'], 0.7, 'civitai', 'owned'),
  ('flatchested-low.safetensors', 'Flatchested-Low', 'krea2', 'both', ARRAY['krea2', 'both'], 0.7, 'civitai', 'owned'),
  ('gay_anal_sex-i2v-High_noise.safetensors', 'Gay Anal Sex-I2V-High Noise', 'krea2', 'both', ARRAY['krea2', 'both'], 0.7, 'civitai', 'owned'),
  ('genital_color_krea2_loraholic.safetensors', 'Genital Color Krea2 Loraholic', 'krea2', 'stills', ARRAY['krea2', 'stills'], 0.7, 'civitai', 'owned'),
  ('genitals-helper.safetensors', 'Genitals-Helper', 'krea2', 'both', ARRAY['krea2', 'both'], 0.7, 'civitai', 'owned'),
  ('genitals_helper_v1.0_e219.safetensors', 'Genitals Helper V1.0 E219', 'krea2', 'both', ARRAY['krea2', 'both'], 0.7, 'civitai', 'owned'),
  ('handpanties-high.safetensors', 'Handpanties-High', 'krea2', 'both', ARRAY['krea2', 'both'], 0.7, 'civitai', 'owned'),
  ('handpanties-low.safetensors', 'Handpanties-Low', 'krea2', 'both', ARRAY['krea2', 'both'], 0.7, 'civitai', 'owned'),
  ('igoon-handed-high.safetensors', 'Igoon-Handed-High', 'krea2', 'both', ARRAY['krea2', 'both'], 0.7, 'civitai', 'owned'),
  ('igoon-handed-low.safetensors', 'Igoon-Handed-Low', 'krea2', 'both', ARRAY['krea2', 'both'], 0.7, 'civitai', 'owned'),
  ('igoon-handjob-high.safetensors', 'Igoon-Handjob-High', 'krea2', 'both', ARRAY['krea2', 'both'], 0.7, 'civitai', 'owned'),
  ('igoon-handjob-low.safetensors', 'Igoon-Handjob-Low', 'krea2', 'both', ARRAY['krea2', 'both'], 0.7, 'civitai', 'owned'),
  ('igoon-missionary-high.safetensors', 'Igoon-Missionary-High', 'krea2', 'both', ARRAY['krea2', 'both'], 0.7, 'civitai', 'owned'),
  ('igoon-missionary-low.safetensors', 'Igoon-Missionary-Low', 'krea2', 'both', ARRAY['krea2', 'both'], 0.7, 'civitai', 'owned'),
  ('krea2_ostris_edit_underboner_v1.safetensors', 'Krea2 Ostris Edit Underboner V1', 'krea2', 'stills', ARRAY['krea2', 'stills'], 0.7, 'civitai', 'owned'),
  ('krea2_uncut_penis_coachbate_v1.safetensors', 'Krea2 Uncut Penis Coachbate V1', 'krea2', 'stills', ARRAY['krea2', 'stills'], 0.7, 'civitai', 'owned'),
  ('labia_minora_krea2_loraholic.safetensors', 'Labia Minora Krea2 Loraholic', 'krea2', 'stills', ARRAY['krea2', 'stills'], 0.7, 'civitai', 'owned'),
  ('male-masturbation.safetensors', 'Male-Masturbation', 'krea2', 'both', ARRAY['krea2', 'both'], 0.7, 'civitai', 'owned'),
  ('mons_pubis_krea2_loraholic.safetensors', 'Mons Pubis Krea2 Loraholic', 'krea2', 'stills', ARRAY['krea2', 'stills'], 0.7, 'civitai', 'owned'),
  ('orgasm-high.safetensors', 'Orgasm-High', 'krea2', 'both', ARRAY['krea2', 'both'], 0.7, 'civitai', 'owned'),
  ('orgasm-low.safetensors', 'Orgasm-Low', 'krea2', 'both', ARRAY['krea2', 'both'], 0.7, 'civitai', 'owned'),
  ('penis_size_krea2_v2_loraholic.safetensors', 'Penis Size Krea2 V2 Loraholic', 'krea2', 'stills', ARRAY['krea2', 'stills'], 0.7, 'civitai', 'owned'),
  ('realism_engine_krea2_v2.safetensors', 'Realism Engine Krea2 V2', 'krea2', 'stills', ARRAY['krea2', 'stills'], 0.7, 'civitai', 'owned'),
  ('undress-all.safetensors', 'Undress-All', 'krea2', 'both', ARRAY['krea2', 'both'], 0.7, 'civitai', 'owned'),
  ('wetness_krea2_loraholic.safetensors', 'Wetness Krea2 Loraholic', 'krea2', 'stills', ARRAY['krea2', 'stills'], 0.7, 'civitai', 'owned'),
  ('cumrag_sd15.safetensors', 'Cumrag Sd15', 'sdxl', 'stills', ARRAY['sdxl', 'stills'], 0.7, 'civitai', 'owned'),
  ('PENISLORA_WAN22_5B_e349.safetensors', 'Penislora Wan22 5B E349', 'wan2.2', 'video', ARRAY['wan2.2', 'video'], 0.7, 'civitai', 'owned'),
  ('Wan2.2-I2V-High-MysticXXX.safetensors', 'Wan2.2-I2V-High-Mysticxxx', 'wan2.2', 'video', ARRAY['wan2.2', 'video'], 0.7, 'civitai', 'owned'),
  ('Wan2.2-Lightning_I2V-A14B-4steps-lora_HIGH_fp16.safetensors', 'Wan2.2-Lightning I2V-A14B-4Steps-Lora High Fp16', 'wan2.2', 'video', ARRAY['wan2.2', 'video'], 0.7, 'civitai', 'owned'),
  ('Wan2.2-Lightning_I2V-A14B-4steps-lora_LOW_fp16.safetensors', 'Wan2.2-Lightning I2V-A14B-4Steps-Lora Low Fp16', 'wan2.2', 'video', ARRAY['wan2.2', 'video'], 0.7, 'civitai', 'owned'),
  ('Wan_2_2_I2V_A14B_HIGH_lightx2v_4step_lora_v1030_rank_64_bf16.safetensors', 'Wan 2 2 I2V A14B High Lightx2V 4Step Lora V1030 Rank 64 Bf16', 'wan2.2', 'video', ARRAY['wan2.2', 'video'], 0.7, 'civitai', 'owned'),
  ('futaTF-high.safetensors', 'Futatf-High', 'wan2.2', 'video', ARRAY['wan2.2', 'video'], 0.7, 'civitai', 'owned'),
  ('futaTF-low.safetensors', 'Futatf-Low', 'wan2.2', 'video', ARRAY['wan2.2', 'video'], 0.7, 'civitai', 'owned'),
  ('js_wan_schoolgirl.safetensors', 'Js Wan Schoolgirl', 'wan2.2', 'video', ARRAY['wan2.2', 'video'], 0.7, 'civitai', 'owned'),
  ('lightx2v_T2V_14B_cfg_step_distill_v2_lora_rank256_bf16.safetensors', 'Lightx2V T2V 14B Cfg Step Distill V2 Lora Rank256 Bf16', 'wan2.2', 'video', ARRAY['wan2.2', 'video'], 0.7, 'civitai', 'owned'),
  ('masturbation_cumshot_v1.1_e310.safetensors', 'Masturbation Cumshot V1.1 E310', 'wan2.2', 'video', ARRAY['wan2.2', 'video'], 0.7, 'civitai', 'owned'),
  ('nsfw22-high.safetensors', 'Nsfw22-High', 'wan2.2', 'video', ARRAY['wan2.2', 'video'], 0.7, 'civitai', 'owned'),
  ('nsfw22-low.safetensors', 'Nsfw22-Low', 'wan2.2', 'video', ARRAY['wan2.2', 'video'], 0.7, 'civitai', 'owned'),
  ('penislora22-high.safetensors', 'Penislora22-High', 'wan2.2', 'video', ARRAY['wan2.2', 'video'], 0.7, 'civitai', 'owned'),
  ('penislora22-low.safetensors', 'Penislora22-Low', 'wan2.2', 'video', ARRAY['wan2.2', 'video'], 0.7, 'civitai', 'owned'),
  ('spanking_for_wan_v1_e128.safetensors', 'Spanking For Wan V1 E128', 'wan2.2', 'video', ARRAY['wan2.2', 'video'], 0.7, 'civitai', 'owned'),
  ('wan-deepthroat.safetensors', 'Wan-Deepthroat', 'wan2.2', 'video', ARRAY['wan2.2', 'video'], 0.7, 'civitai', 'owned'),
  ('wan-erect-penis.safetensors', 'Wan-Erect-Penis', 'wan2.2', 'video', ARRAY['wan2.2', 'video'], 0.7, 'civitai', 'owned'),
  ('wan-french-kissing-tongue.safetensors', 'Wan-French-Kissing-Tongue', 'wan2.2', 'video', ARRAY['wan2.2', 'video'], 0.7, 'civitai', 'owned'),
  ('wan2.2-i2v-high-oral-insertion-v1.0.safetensors', 'Wan2.2-I2V-High-Oral-Insertion-V1.0', 'wan2.2', 'video', ARRAY['wan2.2', 'video'], 0.7, 'civitai', 'owned'),
  ('wan2.2-i2v-low-oral-insertion-v1.0.safetensors', 'Wan2.2-I2V-Low-Oral-Insertion-V1.0', 'wan2.2', 'video', ARRAY['wan2.2', 'video'], 0.7, 'civitai', 'owned'),
  ('wan2.2_ass_slider_v1_low_noise.safetensors', 'Wan2.2 Ass Slider V1 Low Noise', 'wan2.2', 'video', ARRAY['wan2.2', 'video'], 0.7, 'civitai', 'owned'),
  ('wan2.2_i2v_A14b_low_noise_lora_rank64_lightx2v_4step_1022.safetensors', 'Wan2.2 I2V A14B Low Noise Lora Rank64 Lightx2V 4Step 1022', 'wan2.2', 'video', ARRAY['wan2.2', 'video'], 0.7, 'civitai', 'owned'),
  ('wan22-cumshot-aesthetics-low.safetensors', 'Wan22-Cumshot-Aesthetics-Low', 'wan2.2', 'video', ARRAY['wan2.2', 'video'], 0.7, 'civitai', 'owned'),
  ('wan22-frenchkiss-high.safetensors', 'Wan22-Frenchkiss-High', 'wan2.2', 'video', ARRAY['wan2.2', 'video'], 0.7, 'civitai', 'owned'),
  ('wan22-frenchkiss-low.safetensors', 'Wan22-Frenchkiss-Low', 'wan2.2', 'video', ARRAY['wan2.2', 'video'], 0.7, 'civitai', 'owned'),
  ('wan22_i2v_futa_cowgirl_high_noise.safetensors', 'Wan22 I2V Futa Cowgirl High Noise', 'wan2.2', 'video', ARRAY['wan2.2', 'video'], 0.7, 'civitai', 'owned'),
  ('wanghong_v1_000002500.safetensors', 'Wanghong V1 000002500', 'wan2.2', 'video', ARRAY['wan2.2', 'video'], 0.7, 'civitai', 'owned');

ON CONFLICT (worker_filename) DO UPDATE SET
  base_model = EXCLUDED.base_model, lane = EXCLUDED.lane, tags = EXCLUDED.tags, updated_at = now();
