import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — AI Studio",
  description: "The terms governing your use of the AI Studio platform.",
};

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-16">
      <h1 className="text-3xl font-bold tracking-tight">Terms of Service</h1>
      <p className="mt-2 text-sm text-muted-foreground">
        Last updated: September 2, 2026
      </p>

      <div className="mt-8 space-y-6 text-sm leading-relaxed">
        <section>
          <h2 className="text-lg font-semibold">1. Acceptance of Terms</h2>
          <p>
            By accessing or using AI Studio ("the Service"), you agree to be
            bound by these Terms. If you do not agree, do not use the Service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold">2. Eligibility</h2>
          <p>
            You must be at least 18 years old (or the age of majority in your
            jurisdiction) and capable of forming a binding contract to use the
            Service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold">3. Your Content</h2>
          <p>
            You retain ownership of the content you submit to the Service. By
            submitting content, you grant us a limited license to process,
            store, and display it solely to provide the Service to you.
          </p>
          <p className="mt-3">
            You are responsible for the content you generate and represent
            that it does not violate any applicable law or third-party rights.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold">4. Acceptable Use</h2>
          <ul className="list-disc pl-6 space-y-2">
            <li>Do not use the Service for unlawful purposes.</li>
            <li>
              Do not attempt to disrupt, reverse-engineer, or compromise the
              Service or its infrastructure.
            </li>
            <li>
              Do not submit content that infringes others&apos; intellectual
              property, privacy, or publicity rights.
            </li>
            <li>
              Do not misuse accounts, credentials, or access controls.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold">5. AI-Generated Output</h2>
          <p>
            Output generated by AI models is provided &quot;as is&quot; and may
            contain inaccuracies, unintended similarities to existing works, or
            content that does not match your request. You are responsible for
            reviewing output before using it commercially.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold">6. Fees and Payments</h2>
          <p>
            Paid features, if any, are billed according to the plan you select.
            Fees are non-refundable except as required by law. GPU compute is
            billed at cost plus any applicable platform fees.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold">7. Termination</h2>
          <p>
            We may suspend or terminate access to the Service for violations
            of these Terms, abusive use, or as required by law. You may stop
            using the Service at any time.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold">8. Disclaimers</h2>
          <p>
            THE SERVICE IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTIES OF ANY
            KIND, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A
            PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold">9. Limitation of Liability</h2>
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR
            INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES,
            OR FOR LOSS OF PROFITS, DATA, OR GOODWILL ARISING OUT OF OR RELATED
            TO YOUR USE OF THE SERVICE.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold">10. Changes to These Terms</h2>
          <p>
            We may update these Terms from time to time. Material changes will
            be posted on this page with an updated revision date.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold">11. Contact</h2>
          <p>
            Questions about these Terms:{" "}
            <a href="mailto:helloglamourgirl@gmail.com" className="underline">
              helloglamourgirl@gmail.com
            </a>
          </p>
        </section>
      </div>
    </main>
  );
}
